"""PR Creator: Open GitHub PR with audit results."""

import subprocess
import json
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class PRResult:
    success: bool
    pr_url: Optional[str] = None
    pr_number: Optional[int] = None
    error: Optional[str] = None


def create_audit_pr(
    worktree_path: str,
    branch_name: str,
    audit_summary: dict,
    maker_summary: list[str],
    checker_passed: bool,
) -> PRResult:
    """Create a PR using gh pr create with audit details."""
    date_str = datetime.now().strftime("%Y-%m-%d")
    title = f"chore(deps): lint sweep & dependency audit {date_str}"

    body_parts = [
        "## Automated Audit Report\n",
        f"**Date:** {date_str}",
        f"**Branch:** `{branch_name}`\n",
        "### Audit Summary",
        f"- Lint issues found: {audit_summary.get('lint_issues', 0)}",
        f"- Vulnerabilities: {audit_summary.get('vulnerabilities', 0)}",
        f"- Outdated packages: {audit_summary.get('outdated_packages', 0)}",
        f"- Auto-fixable: {audit_summary.get('auto_fixable', 0)}\n",
        "### Maker Actions",
    ]
    if maker_summary:
        for item in maker_summary:
            body_parts.append(f"- {item}")
    else:
        body_parts.append("- No changes applied")

    body_parts.append(f"\n### Checker Verdict: {'PASSED' if checker_passed else 'FAILED'}")

    if checker_passed:
        body_parts.append("\nAll tests pass after changes. Safe to merge.")
    else:
        body_parts.append("\n⚠️ Tests failed. Manual review required.")

    body_parts.append("\n---\n*Auto-generated by Capstone Loop*")
    body = "\n".join(body_parts)

    cmd = [
        "gh", "pr", "create",
        "--title", title,
        "--body", body,
        "--label", "dependencies",
        "--label", "security",
        "--label", "automated",
    ]

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=30, cwd=worktree_path,
        )
        if result.returncode == 0:
            output = result.stdout.strip()
            pr_url = output.split("\n")[-1] if output else None
            pr_number = None
            if pr_url and "/pull/" in pr_url:
                pr_number = int(pr_url.split("/pull/")[-1].strip("/"))
            return PRResult(success=True, pr_url=pr_url, pr_number=pr_number)
        else:
            return PRResult(success=False, error=result.stderr[:500])
    except (subprocess.TimeoutExpired, Exception) as e:
        return PRResult(success=False, error=str(e)[:500])
